import { StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
	container: {
		// backgroundColor: "#fff",
		// justifyContent: "center",
		// padding: 16,
		borderRadius: 20,
		// paddingBottom: 50,
		// marginLeft: 16,
		// marginRight: 16,
		// flex: 1,
		backgroundColor: "#fff",
	},

	image: {
		flex: 1,
		justifyContent: "flex-end",
		alignItems: "center",
		resizeMode: "cover",
	},
	form: {
		alignItems: "center",
		width: "100%",
		backgroundColor: "#fff",
		borderTopRightRadius: 25,
		borderTopLeftRadius: 25,
		marginBottom: 66,
	},
	input: {
		// marginHorizontal: 16,
		padding: 16,
		borderWidth: 1,
		borderColor: "#E8E8E8",
		borderRadius: 8,
		marginBottom: 16,
		backgroundColor: "#F6F6F6",
		width: 300,
	},
	title: {
		fontFamily: "Roboto-Medium",
		fontSize: 30,
		lineHeight: 35,
		textAlign: "center",
		letterSpacing: 0.01,
		color: "#212121",
		marginBottom: 33,
		marginTop: 92,
	},
	button: {
		// marginHorizontal: 16,
		backgroundColor: "#FF6C00",
		borderRadius: 100,
		height: 51,
		paddingLeft: 93,
		paddingRight: 93,
		justifyContent: "center",
		alignItems: "center",
		// marginTop: 43 - 16,
	},
	text: {
		// fontFamily: "Roboto-Regular",
		// fontSize: 16,
		color: "#212121",
	},
	subscribe: {
		marginTop: 16,
		flexDirection: "row",
		alignSelf: "center",
		textAlign: "center",
	},
	loginLink: {
		fontSize: 16,
		color: "#1B4371",
		// textDecoration: underline,
	},
	avatarWrapper: {
		width: 120,
		height: 120,
		backgroundColor: "#F6F6F6",
		borderRadius: 16,
		position: "absolute",
		// left: 128,
		top: -60,
		alignSelf: "center",
	},
	icon: {
		top: 70,
		left: 105,
	},
});

//   container: {
//     flex: 1,
//     backgroundColor: "#fff",
//   },
//   imgBg: {
//     flex: 1,
//     resizeMode: "cover",
//     alignItems: "center",
//     justifyContent: "flex-end",
//   },
//   form: {
//     alignItems: "center",
//     width: "100%",
//     backgroundColor: "#fff",
//     borderTopRightRadius: 25,
//     borderTopLeftRadius: 25,
//   },
//   addAvatar: {
//     marginTop: -60,
//     width: 132,
//     height: 120,
//     backgroundColor: "#F6F6F6",
//     borderRadius: 16,
//   },
//   addAvatarBtn: {
//     marginTop: 81,
//     marginLeft: 119.5,
//     alignItems: "center",
//     justifyContent: "center",
//   },
//   title: {
//     fontFamily: "Roboto-Medium",
//     fontSize: 30,
//     paddingVertical: 32,
//     letterSpacing: 0.2,
//     lineHeight: 35,
//   },
//   formInput: {
//     gap: 16,
//   },
//   input: {
//     fontSize: 16,
//     width: 343,
//     height: 50,
//     backgroundColor: "#F6F6F6",
//     color: "#000",
//     borderRadius: 8,
//     borderWidth: 1,
//     borderColor: "#E8E8E8",
//     paddingLeft: 16,
//   },
//   passwordInput: {
//     flexDirection: "row",
//     alignItems: "center",
//   },
//   showPasswordBtn: {
//     marginLeft: -60,
//   },
//   loginBtn: {
//     alignItems: "center",
//     justifyContent: "center",
//     width: 343,
//     height: 50,
//     backgroundColor: "#FF6C00",
//     marginTop: 43,
//     borderRadius: 100,
//   },
//   loginBtnTitle: {
//     fontSize: 16,
//     lineHeight: 19,
//     color: "#fff",
//   },
//   isAccount: {
//     marginTop: 16,
//   },
//   isAccountText: {
//     fontSize: 16,
//     color: "#1B4371",
//   },
// });
